version: '3'
services:
  # myapp:
  #   image:
  #    377029775554.dkr.ecr.us-east-1.amazonaws.com/myapp:v1.1
  #   ports:
  #    - 8000:8000
  #   environment:
  #    - PORT=8000
  #    - MONGODB_URL=mongodb://admin:password@165.232.189.19:27017/users?authSource=admin
  mongodb:
    image:
      mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image:
      mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart:
      always
    depends_on:
      - mongodb
volumes:
  mongo-data: # Name of the volume
    driver: local # It is an indication that docker should create that storage on host local file system.
